sudo: required
services:
  - docker

before_install:
  - docker build -t lithium366/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true lithium366/react-test npm run test

after_success:
  - docker build -t lithium366/multi-client ./client
  - docker build -t lithium366/multi-server ./server
  - docker build -t lithium366/multi-worker ./worker
  - docker build -t lithium366/multi-nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" -- password-stdin
  - docker push lithium366/multi-client
  - docker push lithium366/multi-server
  - docker push lithium366/multi-worker
  - docker push lithium366/multi-nginx
